trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
      - job: job1
        steps:
          - script: echo hello world
            displayName: 'running one line script'
          - script: echo hello ji
            displayName: 'running one line script'

      - job: job2
        steps:
          - script: |
              echo another work
              echo abcde
            displayName: 'running multiple script'

      - job: job3  
        steps:
          - bash: this is job3
          

          


