

trigger:
  master
pool:
  vmImage: Ubuntu-latest

stages:
-stage: Dev
 jobs:
  -job: Job1
    steps:
    - script: echo hello world
      displayName: 'running a one line script'
  - job: Job2
    steps:
    - script: |
      echo add tasks to build
      echo see link
      echo abcd
      
  -job: Job3 
    steps:
    -script: bcda
