trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
      - job: job1
        steps:
          - script: echo hello world
            displayName: 'running one line script'
          - script: echo hello ji
            displayName: 'running one line script'
      - job: job2
        dependsOn: job1
        steps:
          - script: |
              echo another work
              echo abcde
            displayName: 'running multiple script'
      - job: job3  
        dependsOn: job1
        steps:
        - bash: echo this is from job3
      - job: job4  
        dependsOn: 
        - job2
        - job3
        steps:
        - script: echo this is from job4
          displayName: 'running last job from github'
          

          

